version: "3.9"

services:
  backend:
    build: ./backend
    container_name: helios-backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5000"

  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    container_name: helios-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
